# A workflow which creates a package optimal for FetchContent

name: Make package

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure cmake
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DGLM_BUILD_PACKAGE=ON -DGLM_BUILD_TESTS=OFF -DGLM_BUILD_INSTALL=OFF -DGLM_BUILD_LIBRARY=OFF

    - name: Create Package
      working-directory: build/
      run: cmake --build . --target glm_package

    - name: Add to release
      uses: softprops/action-gh-release@v1
      with:
        files: build/glm-${{ env.RELEASE_VERSION }}-src.zip
